### ISSUE TITLE
How to choose softdevice

### ISSUE THREAD

**Issue by WCCWCC** [Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks#3]
@Matheus-Garbelini ，
I cannot flash the hex program to the device by nRF Connect.

DFU failed: Error message for known extended error code from DFU target: The array of supported SoftDevices for the update does not contain the FWID of the current SoftDevice.
16:58:27.693	Device not found due to failure during DFU

![图片](https://user-images.githubusercontent.com/47855814/76399829-46bbc880-63ba-11ea-805b-70efc14f7ce9.png)

**Comment by Matheus-Garbelini** [comment]
Hi @WCCWCC I've just added the hex code of the [softdevice](https://github.com/Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks/blob/master/s140_nrf52_6.1.1_softdevice.hex) on this repo. for convenience.

You can also fastly flash the firmware by simply running the following commands instead of using the nRF programmer:
```Shell
python -m pip install nrfutil
nrfutil dfu usb-serial -p COM_PORT -pkg nRF52_driver_firmware.zip
```
Remember to put the device in DFU mode and change the COM_PORT parameter to match your dongle.
